---
- name: Set default shell (osx)
  command: chsh -s "{{ default_shell }}"
  when: ansible_os_family == 'Darwin'

- name: Set default shell (linux)
  user:
    name: "{{ lookup('env','USER') }}"
    shell: "{{ default_shell }}"
  become: yes
  when: ansible_os_family == 'Debian'

- name: Create local_bin folder
  file:
    path: ~/local_bin
    state: directory
    force: no
