---
- name: Set default shell
  command: chsh -s "{{ default_shell }}"

- name: Create local_bin folder
  file:
    path: ~/local_bin
    state: directory
    force: no

- name: Create ~/DEV folder
  file:
    path: ~/DEV
    state: directory
    force: no