---
- hosts: localhost

  vars:
    dotfiles_installation_path: "$HOME/dotfiles"
    
  roles:
    - { role: git_setup }
    - { role: symlink_dotfiles }
    - { role: system_settings }
    - { role: homebrew, when: ansible_os_family == 'Darwin' }
    - { role: osx_defaults, when: ansible_os_family == 'Darwin' }
    - { role: osx_updates, when: ansible_os_family == 'Darwin' }
