---
- hosts: localhost

  vars:
    dotfiles_installation_path: "$HOME/dotfiles"

  vars_prompt:
  - name: "git_name"
    prompt: "What is your git use name?"
  - name: "git_email"
    prompt: "what is your github email?"

  roles:
    - { role: symlink_dotfiles }
    - { role: git_setup }
    - { role: homebrew }
    - { role: osx_defaults }
    - { role: osx_updates }
