cask_args appdir: '/Applications'

brew 'git'
brew 'coreutils'
brew 'go'
brew 'jq'
brew 'node'
brew 'openssl'
brew 'python'
brew 'python3'
brew 'tmux'

cask 'cinch'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'vagrant'
cask 'visual-studio-code"
cask 'vlc'
